branches:
  only:
    - master
language: ruby
cache:
  bundler: true
  yarn: true
install:
  - gem install bundler
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - bundle exec rails db:test:load
script:
  - bundle exec rails test
# TODO: add precompile and deploy after ssh is setup
# after_success:
  # - bundle exec rails assets:precompile
notifications:
  email: false
